text.color = color.black
text.backColor = color.white
clear
print "    _     _"
print "   (c).-.(c)"
print "    / ._. \"
print "  __\( Y )/__"
print " (_.-/'-'\-._)"
print "    || x ||"
print "  _.' '-' '._"
print " (.-./'-~\.-.)"
print "  '-'     '-'"
text.setCellColor 7, 20, color.gray  // belly button
text.setCellColor 6, 23, color.blue  // left eye
text.setCellColor 8, 23, color.blue  // right eye
